# Generated by Django 2.2.28 on 2022-08-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20220819_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
    ]
